# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def GenerateFollowUpQuestions(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.Question"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateFollowUpQuestions", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.Question"], result)

    def GenerateSpecificationFromTemplate(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.Question", "types.WebsiteSpecification"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateSpecificationFromTemplate", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.Question", "types.WebsiteSpecification"], result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def GenerateFollowUpQuestions(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.Question"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateFollowUpQuestions", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.Question"], result)

    def GenerateSpecificationFromTemplate(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.Question", "stream_types.WebsiteSpecification"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="GenerateSpecificationFromTemplate", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.Question", "stream_types.WebsiteSpecification"], result)

    