# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.LLMMessage": types.LLMMessage,
    "stream_types.LLMMessage": stream_types.LLMMessage,

    "types.Question": types.Question,
    "stream_types.Question": stream_types.Question,

    "types.WebsiteSpecification": types.WebsiteSpecification,
    "stream_types.WebsiteSpecification": stream_types.WebsiteSpecification,


}