# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetermineFilesToEdit(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.FileList:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DetermineFilesToEdit", llm_response=llm_response, mode="request")
        return typing.cast(types.FileList, __result__)

    def GenerateSearchReplaceBlocks(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateSearchReplaceBlocks", llm_response=llm_response, mode="request")
        return typing.cast(str, __result__)

    def UserResponseOrCoder(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["types.ResponseToUser", "types.Coder"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="UserResponseOrCoder", llm_response=llm_response, mode="request")
        return typing.cast(typing.Union["types.ResponseToUser", "types.Coder"], __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def DetermineFilesToEdit(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.FileList:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="DetermineFilesToEdit", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.FileList, __result__)

    def GenerateSearchReplaceBlocks(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="GenerateSearchReplaceBlocks", llm_response=llm_response, mode="stream")
        return typing.cast(str, __result__)

    def UserResponseOrCoder(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.Union["stream_types.ResponseToUser", "stream_types.Coder"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="UserResponseOrCoder", llm_response=llm_response, mode="stream")
        return typing.cast(typing.Union["stream_types.ResponseToUser", "stream_types.Coder"], __result__)

    