# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (0)
# #########################################################################

# #########################################################################
# Generated classes (4)
# #########################################################################

class Coder(BaseModel):
    coder_request: str = Field(description='At most one short sentence for coder agent. Coder agent has the full conversation context so don\'t provide details. For example: \'Build the website\' or \'Fix the bug\' or \'Add the new section\'')

class FileList(BaseModel):
    reasoning: str = Field(description='Explanation of why these files need to be edited or not in one short sentence.')
    files: typing.List[str] = Field(description='List of file paths to edit.')

class LLMMessage(BaseModel):
    role: typing.Union[typing_extensions.Literal['user'], typing_extensions.Literal['assistant']]
    content: str

class ResponseToUser(BaseModel):
    response: str = Field(description='Response to user from chat agent')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
